print("=== Aplikasi Biodata===")
name = input ("masukian nama: ")
gender = input ("masukan gender: ")
tanggal_lahir = input ("masukan tanggal lahir: ")
hobi = input ("masukan hobi: ")

print("nama : ", name)
print("gender : ", gender)
print("tanggal lahir : ", tanggal_lahir)
print("hobi: ", hobi)